locale: "en-US"
title: "Yunfan Xie (Ryan)"
name: "Yunfan Xie (Ryan)"
url: "https://ryanyunfanxie.github.io"
baseurl: ""
repository: "ryanyunfanxie/ryanyunfanxie.github.io"
timezone: "Asia/Hong_Kong"

author:
  name: "Yunfan Xie (Ryan)"
  email: "yxiecc@connect.ust.hk"
  github: "ryanyunfanxie"

include:
  - _pages

exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - local
  - vendor

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

plugins:
  - jekyll-sitemap
